/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coe528.project;

import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 * GUI FOR LOGIN AND SIGNUP
 * @author pasindu
 */
public class Login extends javax.swing.JDialog {


    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerLoginButton = new javax.swing.JButton();
        newCustomerButton = new javax.swing.JButton();
        managerLoginButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        customerLoginButton.setText("Customer Login");
        customerLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerLoginButtonActionPerformed(evt);
            }
        });

        newCustomerButton.setText("New Customer SignUp");
        newCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCustomerButtonActionPerformed(evt);
            }
        });

        managerLoginButton.setText("Manager Login");
        managerLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerLoginButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(managerLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(newCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(customerLoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerLoginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newCustomerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(managerLoginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void customerLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerLoginButtonActionPerformed
        
        JTextField usernameField = new JTextField(5);
        JPasswordField passwordField = new JPasswordField(5);
        JPanel loginPanel = new JPanel();
        loginPanel.setLayout(new BoxLayout(loginPanel, BoxLayout.Y_AXIS));               
        loginPanel.add(new JLabel("Username: "));
        loginPanel.add(usernameField);
        loginPanel.add(Box.createVerticalStrut(5));
        loginPanel.add(new JLabel("Password: "));
        loginPanel.add(passwordField);
      

        int userinput = JOptionPane.showConfirmDialog(this, loginPanel, "Username & Password", JOptionPane.OK_CANCEL_OPTION);
        if (userinput == JOptionPane.OK_OPTION) {
           String username=usernameField.getText();
           String password=passwordField.getText();
           if(username.equals("")){
                   JOptionPane.showMessageDialog(this, "Invaid Username & Password", "Login Error",JOptionPane.ERROR_MESSAGE); 
                   return;
           }
           for(User c:POS_SystemV1.getAllCustomers()){
               if(c.getUserName().equals(username) && c.getPassword().equals(password)){
                   POS_SystemV1.setActiveUser(c);
                   this.dispose();
                   return;
                   
               }             
           }
           JOptionPane.showMessageDialog(this, "Username or Password is incorrect", "Login Error",JOptionPane.ERROR_MESSAGE);  
        }
      
      
    }//GEN-LAST:event_customerLoginButtonActionPerformed

    private void newCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCustomerButtonActionPerformed
        JTextField newUsernameField = new JTextField(5);
        JPasswordField new1PasswordField = new JPasswordField(5);
        JPasswordField new2PasswordField = new JPasswordField(5);
        JPanel signupPanel = new JPanel();
        signupPanel.setLayout(new BoxLayout(signupPanel, BoxLayout.Y_AXIS));               
        signupPanel.add(new JLabel("New Username: "));
        signupPanel.add(newUsernameField);
        signupPanel.add(Box.createVerticalStrut(5));
        signupPanel.add(new JLabel("New Password: "));
        signupPanel.add(new1PasswordField);
        signupPanel.add(Box.createVerticalStrut(5));
        signupPanel.add(new JLabel("Confirm New Password: "));
        signupPanel.add(new2PasswordField);
      

        int userinput = JOptionPane.showConfirmDialog(this, signupPanel,"SignUp Form", JOptionPane.OK_CANCEL_OPTION);
        if (userinput == JOptionPane.OK_OPTION) {
           String newUsername=newUsernameField.getText();
           String password1=new1PasswordField.getText();
           String password2=new2PasswordField.getText();
           //System.out.println("Username:"+username);
           //System.out.println("Password:"+password);
           if(newUsername.equals("")){
                   JOptionPane.showMessageDialog(this, "Invaid Username & Password", "SignUp Error",JOptionPane.ERROR_MESSAGE); 
                   return;
           }
           for(User c:POS_SystemV1.getAllCustomers()){
               if(c.getUserName().equals(newUsername)){
                   JOptionPane.showMessageDialog(this, "Username Already Exists", "SignUp Error",JOptionPane.ERROR_MESSAGE); 
                   return;
               }             
           }
           if(!password1.equals(password2)){
               JOptionPane.showMessageDialog(this, "Password Confirmation Doesn't Match", "SignUp Error",JOptionPane.ERROR_MESSAGE);
               return;
           }
           
           User newCustomer=new Customer(newUsername, password1);
           POS_SystemV1.getAllCustomers().add(newCustomer);
           POS_SystemV1.setActiveUser(newCustomer);
           this.dispose();
           
        }
    }//GEN-LAST:event_newCustomerButtonActionPerformed

    private void managerLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerLoginButtonActionPerformed
         JTextField usernameField = new JTextField(5);
        JPasswordField passwordField = new JPasswordField(5);
        JPanel loginPanel = new JPanel();
        loginPanel.setLayout(new BoxLayout(loginPanel, BoxLayout.Y_AXIS));               
        loginPanel.add(new JLabel("Manager Username: "));
        loginPanel.add(usernameField);
        loginPanel.add(Box.createVerticalStrut(5));
        loginPanel.add(new JLabel("Manager Password: "));
        loginPanel.add(passwordField);
      

        int userinput = JOptionPane.showConfirmDialog(this, loginPanel, "Enter Manager Username & Password", JOptionPane.OK_CANCEL_OPTION);
        if (userinput == JOptionPane.OK_OPTION) {
           String username=usernameField.getText();
           String password=passwordField.getText();
           //System.out.println("Username:"+username);
           //System.out.println("Password:"+password);
           if(username.equals("")){
                   JOptionPane.showMessageDialog(this, "Invaid Manager Username & Password", "Manager Login Error",JOptionPane.ERROR_MESSAGE); 
                   return;
           }
           User m=POS_SystemV1.getManager();
            if(m.getUserName().equals(username) && m.getPassword().equals(password)){
                POS_SystemV1.setActiveUser(m);
                this.dispose();
                return;
            }             
           JOptionPane.showMessageDialog(this, "Username or Password is incorrect", "Manager Login Error",JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_managerLoginButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customerLoginButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton managerLoginButton;
    private javax.swing.JButton newCustomerButton;
    // End of variables declaration//GEN-END:variables
}
