/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coe528.project;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * GUI FOR PAYMENT
 * @author pasindu
 */
public class PaymentGUI extends javax.swing.JDialog {
    
    private double netTotal;
    private double paymentTotal;
    private int couponNumber;

    
    public PaymentGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        setLocationRelativeTo(parent);
        initComponents();
        this.handingTotalFormattedTextField.setEnabled(false);
        this.handingTotalLabel.setVisible(false);
        this.creditCardNoFormattedTextField.setEnabled(false);
        this.creditCardNoLabel.setVisible(false);
        this.payButton.setEnabled(false);
        pack();
    }
    
    public PaymentGUI(java.awt.Frame parent, boolean modal,String netTotal, String paymentTotal, int couponNumber) {
        this(parent, modal);
        this.netTotalLabel.setText("Net Total: "+netTotal);
        this.totalPaymentLabel.setText("Payment Total: "+paymentTotal);
        this.couponNumber=couponNumber;
        this.netTotal=Double.parseDouble(netTotal.substring(netTotal.indexOf("$ ")+1));
        this.paymentTotal=Double.parseDouble(paymentTotal.substring(paymentTotal.indexOf("$ ")+1));
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cashRadioButton = new javax.swing.JRadioButton();
        creditRadioButton = new javax.swing.JRadioButton();
        handingTotalLabel = new javax.swing.JLabel();
        creditCardNoLabel = new javax.swing.JLabel();
        creditCardNoFormattedTextField = new javax.swing.JFormattedTextField();
        handingTotalFormattedTextField = new javax.swing.JFormattedTextField();
        netTotalLabel = new javax.swing.JLabel();
        totalPaymentLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        payButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Check Out - Payment");
        setResizable(false);

        buttonGroup.add(cashRadioButton);
        cashRadioButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        cashRadioButton.setText("Cash");
        cashRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup.add(creditRadioButton);
        creditRadioButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        creditRadioButton.setText("Credit");
        creditRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditRadioButtonActionPerformed(evt);
            }
        });

        handingTotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        handingTotalLabel.setText("Handing Total   :");
        handingTotalLabel.setFocusable(false);
        handingTotalLabel.setInheritsPopupMenu(false);
        handingTotalLabel.setRequestFocusEnabled(false);
        handingTotalLabel.setVerifyInputWhenFocusTarget(false);

        creditCardNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        creditCardNoLabel.setText("Credit Card No  :");

        try {
            creditCardNoFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        creditCardNoFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        handingTotalFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        netTotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        netTotalLabel.setText("Net Total:");
        netTotalLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        totalPaymentLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalPaymentLabel.setText("Total Payment:");
        totalPaymentLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cashRadioButton)
                            .addComponent(creditRadioButton))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(creditCardNoLabel)
                            .addComponent(handingTotalLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(creditCardNoFormattedTextField)
                            .addComponent(handingTotalFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(netTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(totalPaymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(netTotalLabel)
                    .addComponent(totalPaymentLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashRadioButton)
                    .addComponent(handingTotalLabel)
                    .addComponent(handingTotalFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditRadioButton)
                    .addComponent(creditCardNoLabel)
                    .addComponent(creditCardNoFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        payButton.setText("Pay");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cashRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashRadioButtonActionPerformed
        this.handingTotalFormattedTextField.setEnabled(true);
        this.handingTotalLabel.setVisible(true);
        this.creditCardNoFormattedTextField.setEnabled(false);
        this.creditCardNoLabel.setVisible(false);
        this.payButton.setEnabled(true);
    }//GEN-LAST:event_cashRadioButtonActionPerformed

    private void creditRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditRadioButtonActionPerformed
        this.handingTotalFormattedTextField.setEnabled(false);
        this.handingTotalLabel.setVisible(false);
        this.creditCardNoFormattedTextField.setEnabled(true);
        this.creditCardNoLabel.setVisible(true);
        this.payButton.setEnabled(true);
    }//GEN-LAST:event_creditRadioButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        CustomerGUI.setCheckOutSuccessful(false);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        if(cashRadioButton.isSelected()){
            if(this.handingTotalFormattedTextField.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Invaid Entry For Handing Total", "Payment Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            double handingTotal=Double.parseDouble(this.handingTotalFormattedTextField.getText());
            if(handingTotal<0.0){
                JOptionPane.showMessageDialog(this, "Invaid Entry For Handing Total", "Payment Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(handingTotal<paymentTotal){
                JOptionPane.showMessageDialog(this, "Not Suffient Money To Pay", "Payment Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            ArrayList<MenuItem> temp=new ArrayList<MenuItem>();
            for(MenuItem m:POS_SystemV1.getActiveUser().getBasket()){
                temp.add(m.clone());
            }
            Transaction t=new Transaction((Customer)POS_SystemV1.getActiveUser(), temp, handingTotal, couponNumber);
            POS_SystemV1.getActiveUser().getTransaction_list().add(t);
            POS_SystemV1.getAllTractions().add(t);
            JOptionPane.showMessageDialog(this, "Transaction Completed\n<<< Summery >>>\n"+t.toString().replaceAll("\t", "\n"), "Payment Successful", JOptionPane.INFORMATION_MESSAGE);
            CustomerGUI.setCheckOutSuccessful(true);
            this.dispose();
            
            
        }
        if(creditRadioButton.isSelected()){
            String CC=this.creditCardNoFormattedTextField.getText();
            if(CC.trim().length()<14){
                JOptionPane.showMessageDialog(this, "Invaid Credit Card Number", "Payment Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            ArrayList<MenuItem> temp=new ArrayList<MenuItem>();
            for(MenuItem m:POS_SystemV1.getActiveUser().getBasket()){
                temp.add(m.clone());
            }
            Transaction t=new Transaction((Customer)POS_SystemV1.getActiveUser(),temp, CC, couponNumber);
            POS_SystemV1.getActiveUser().getTransaction_list().add(t);
            POS_SystemV1.getAllTractions().add(t);
            JOptionPane.showMessageDialog(this, "Transaction Completed\n<<< Summery >>>\n"+t.toString().replaceAll("\t", "\n"), "Payment Successful", JOptionPane.INFORMATION_MESSAGE);
            CustomerGUI.setCheckOutSuccessful(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_payButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton cashRadioButton;
    private javax.swing.JFormattedTextField creditCardNoFormattedTextField;
    private javax.swing.JLabel creditCardNoLabel;
    private javax.swing.JRadioButton creditRadioButton;
    private javax.swing.JFormattedTextField handingTotalFormattedTextField;
    private javax.swing.JLabel handingTotalLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel netTotalLabel;
    private javax.swing.JButton payButton;
    private javax.swing.JLabel totalPaymentLabel;
    // End of variables declaration//GEN-END:variables
}
